### ISSUE TITLE
Meta-issue of styling

### ISSUE THREAD

**Issue by jackvreeken** [pymoca/pymoca#283]
- [x] black
- [x] flake all but E501 (line too long)
- [ ] Git blame ignore file
- [ ] test case for the bug
- [ ] remove Python 2 backwards compatibility stuff (`from future import`)
- [ ] OrderedDict -> dict (because minimum Python version is 3.8, in which dict is guaranteed ordered)
- [ ] type annotations as comments (because python 2) to proper Python 3 annotations. Just the ones that are there, not new ones. Ands get rid of the `noqa: F401` I had to add
- [ ] flake including E501
- [ ] Things that PyCharm reports?
- [ ] Maybe split the `gen_casadi_test` fixes with "self.assertRaisesRegex" to separate commit?
- [ ] Also strictly not style, the double import in gen_sympy_test of print_function

Especially in `gen_casadi_test` I have a bunch of `noqa: F841`. This is because some models have variables that becomes aliases. I think it's prettier that it is indeed then a variable that is unused in Python as well.
I'm still on the fence about F841 for other variables that aren't used, e.g. `casadi_model = ...`. It's easy it's already there when debugging tests, but how often does that happen?

**Comment by kentrutan** [comment]
@jackvreeken I updated the styling todo list with pointers to use the pyupgrade and com2ann tools that should automatically fix some code cleanup.
